import './globals.css'
import { FC, ReactNode } from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export interface Props {
	readonly children: ReactNode
}

const Component: FC<Props> = ({ children}) =>
	<html lang='en'>
		<body>
			{children}
		</body>
	</html>

export default Component
